/** Client-side export — the decision document leaves as Markdown or raw JSON.
 * Built entirely from run state (Helix build_markdown idiom, no backend round-trip).
 */

import { agentById } from "./agents";
import type { BoardItem, Verdict } from "./types";

interface ExportInput {
  brief: Record<string, unknown> | null;
  verdict: Verdict | null;
  board: BoardItem[];
  agentOutputs: Record<string, Record<string, unknown>>;
  tokens: number;
  routes: Set<string>;
}

export function buildMarkdown(s: ExportInput): string {
  const v = s.verdict;
  if (!v) return "# EIP — no verdict yet\n";
  const b = s.brief ?? {};
  const claims = s.board.filter((x) => x.kind === "claim" && x.source?.url);
  const conflicts = s.board.filter((x) => x.kind === "conflict");
  const biases = s.board.filter((x) => x.kind === "bias");
  const lines: string[] = [
    `# EIP Decision Document`,
    ``,
    `> ${String(b.summary ?? "")}`,
    ``,
    `**Verdict: ${v.recommendation} — ${v.score}/10** (${v.band})`,
    ``,
    v.reasoning,
    ``,
    `## Dimensions`,
    ``,
    ...Object.entries(v.dimensions ?? {}).map(([k, d]) => `- ${k}: **${d}/10**`),
    ``,
    `## What would change this verdict`,
    ``,
    ...(v.sensitivities ?? []).map((x, i) => `${i + 1}. ${x}`),
    ``,
    `## Risk register`,
    ``,
    ...(v.risks ?? []).map((r) => `- **[${agentById(r.source_agent).name}]** ${r.text}`),
    ``,
    `## Opportunities & next steps`,
    ``,
    ...(v.opportunities ?? []).map((o) => `- ${o.text}`),
    ...(v.next_steps ?? []).map((x) => `- [ ] ${x}`),
    ``,
    `## Where agents disagreed`,
    ``,
    ...(conflicts.length
      ? conflicts.map((c) => `- ⚔ **${agentById(c.agent).name}** vs **${agentById(c.vs ?? "").name}**: ${c.text}`)
      : ["_No open conflicts recorded._"]),
    ``,
    `## Bias flags on your framing`,
    ``,
    ...(biases.length ? biases.map((f) => `- ⚑ ${f.text}`) : ["_None detected._"]),
    ``,
    `## Evidence (${claims.length} sourced claims)`,
    ``,
    ...claims.map((c) => `- ${c.text} — [${c.source?.name || "source"}](${c.source?.url})`),
    ``,
    `---`,
    ``,
    v.teach ? `**How to think about this:** ${v.teach}\n` : ``,
    `_Generated by EIP · ${s.tokens.toLocaleString()} tokens · ${[...s.routes].join(", ") || "deterministic cores only"}._`,
    ``,
    `_EIP provides analytics and education, not investment advice. Decisions and outcomes are yours._`,
  ];
  return lines.join("\n");
}

export function download(filename: string, content: string, type = "text/markdown"): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
