/** Client-side export — the decision document leaves as Markdown or raw JSON.
 * Built entirely from run state (Helix build_markdown idiom, no backend round-trip).
 */

import { agentById } from "./agents";
import type { BoardItem, Verdict } from "./types";

interface ExportInput {
  brief: Record<string, unknown> | null;
  verdict: Verdict | null;
  board: BoardItem[];
  agentOutputs: Record<string, Record<string, unknown>>;
  tokens: number;
  routes: Set<string>;
}

export function buildMarkdown(s: ExportInput): string {
  const v = s.verdict;
  if (!v) return "# EIP — no verdict yet\n";
  const b = s.brief ?? {};
  const claims = s.board.filter((x) => x.kind === "claim" && x.source?.url);
  const conflicts = s.board.filter((x) => x.kind === "conflict");
  const biases = s.board.filter((x) => x.kind === "bias");
  const lines: string[] = [
    `# EIP Decision Document`,
    ``,
    `> ${String(b.summary ?? "")}`,
    ``,
    `**Verdict: ${v.recommendation} — ${v.score}/10** (${v.band})`,
    ``,
    v.reasoning,
    ``,
    `## Dimensions`,
    ``,
    ...Object.entries(v.dimensions ?? {}).map(([k, d]) => `- ${k}: **${d}/10**`),
    ``,
    `## What would change this verdict`,
    ``,
    ...(v.sensitivities ?? []).map((x, i) => `${i + 1}. ${x}`),
    ``,
    `## Risk register`,
    ``,
    ...(v.risks ?? []).map((r) => `- **[${agentById(r.source_agent).name}]** ${r.text}`),
    ``,
    `## Opportunities & next steps`,
    ``,
    ...(v.opportunities ?? []).map((o) => `- ${o.text}`),
    ...(v.next_steps ?? []).map((x) => `- [ ] ${x}`),
    ``,
    `## Where agents disagreed`,
    ``,
    ...(conflicts.length
      ? conflicts.map((c) => `- ⚔ **${agentById(c.agent).name}** vs **${agentById(c.vs ?? "").name}**: ${c.text}`)
      : ["_No open conflicts recorded._"]),
    ``,
    `## Bias flags on your framing`,
    ``,
    ...(biases.length ? biases.map((f) => `- ⚑ ${f.text}`) : ["_None detected._"]),
    ``,
    `## Evidence (${claims.length} sourced claims)`,
    ``,
    ...claims.map((c) => `- ${c.text} — [${c.source?.name || "source"}](${c.source?.url})`),
    ``,
    `---`,
    ``,
    v.teach ? `**How to think about this:** ${v.teach}\n` : ``,
    `_Generated by EIP · ${s.tokens.toLocaleString()} tokens · ${[...s.routes].join(", ") || "deterministic cores only"}._`,
    ``,
    `_EIP provides analytics and education, not investment advice. Decisions and outcomes are yours._`,
  ];
  return lines.join("\n");
}

export function download(filename: string, content: string, type = "text/markdown"): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Print-to-PDF: renders the decision document as a clean printable page and
 * opens the browser print dialog (Save as PDF). No dependency, works offline. */
export function printPdf(s: ExportInput): void {
  const v = s.verdict;
  if (!v) return;
  const esc = (t: unknown) =>
    String(t).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const claims = s.board.filter((x) => x.kind === "claim" && x.source?.url);
  const rows = Object.entries(s.agentOutputs)
    .filter(([, o]) => typeof o.score === "number")
    .sort((a, b) => (b[1].score as number) - (a[1].score as number));
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>EIP Decision</title>
  <style>
    body{font:13px/1.55 -apple-system,Segoe UI,Roboto,sans-serif;color:#111;max-width:800px;margin:32px auto;padding:0 24px}
    h1{font-size:22px;margin:0 0 4px} h2{font-size:15px;margin:22px 0 8px;border-bottom:1px solid #ddd;padding-bottom:4px}
    .verdict{font-size:26px;font-weight:700} .band{display:inline-block;padding:2px 10px;border:1px solid #999;border-radius:6px;font-size:13px}
    table{width:100%;border-collapse:collapse;font-size:11px} td,th{border-bottom:1px solid #eee;padding:4px 6px;text-align:left}
    .dim{display:inline-block;border:1px solid #ccc;border-radius:5px;padding:2px 8px;margin:2px;font-size:11px}
    .muted{color:#777;font-size:10px} a{color:#0a6}
    @media print{body{margin:0}}
  </style></head><body>
  <h1>EIP Decision Document</h1>
  <div class="muted">${esc(s.brief?.summary ?? "")}</div>
  <p><span class="verdict">${esc(v.score)}/10</span> &nbsp; <span class="band">${esc(v.recommendation)}</span></p>
  <p>${esc(v.reasoning)}</p>
  <h2>Dimensions</h2>
  <div>${Object.entries(v.dimensions ?? {}).map(([k, d]) => `<span class="dim">${esc(k)}: ${esc(d)}/10</span>`).join("")}</div>
  <h2>What would change this verdict</h2>
  <ol>${(v.sensitivities ?? []).map((x) => `<li>${esc(x)}</li>`).join("")}</ol>
  <h2>The board — ${rows.length} specialists</h2>
  <table><thead><tr><th>specialist</th><th>score</th><th>finding</th></tr></thead><tbody>
  ${rows.map(([id, o]) => `<tr><td>${esc(agentById(id).name)}</td><td>${esc(o.score)}/10</td><td>${esc(String(o.verdict_line ?? "").slice(0, 120))}</td></tr>`).join("")}
  </tbody></table>
  <h2>Risks</h2>
  <ul>${(v.risks ?? []).map((r) => `<li><b>[${esc(agentById(r.source_agent).name)}]</b> ${esc(r.text)}</li>`).join("")}</ul>
  <h2>Next steps</h2>
  <ol>${(v.next_steps ?? []).map((x) => `<li>${esc(x)}</li>`).join("")}</ol>
  <h2>Evidence — ${claims.length} sourced claims</h2>
  <ul>${claims.slice(0, 30).map((c) => `<li>${esc(c.text)} — <a href="${esc(c.source?.url)}">${esc(c.source?.name ?? "source")}</a></li>`).join("")}</ul>
  <p class="muted">Generated by EIP · ${s.tokens.toLocaleString()} tokens · ${[...s.routes].join(", ") || "deterministic cores"}. EIP provides analytics and education, not investment advice.</p>
  </body></html>`;
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  setTimeout(() => w.print(), 400);
}
